"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

export default function ResetPasswordPage() {
  const router = useRouter();
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [ready, setReady] = useState(false);
  const [firstLogin, setFirstLogin] = useState(false);
  const [tokenHash, setTokenHash] = useState<string | null>(null);

  useEffect(() => {
    const supabase = createClient();
    let mounted = true;
    setFirstLogin(new URLSearchParams(window.location.search).get("first_login") === "1");

    async function prepareRecoverySession() {
      const searchParams = new URLSearchParams(window.location.search);
      const code = searchParams.get("code");
      const recoveryTokenHash = searchParams.get("token_hash");
      if (recoveryTokenHash) setTokenHash(recoveryTokenHash);
      if (code) {
        const { error: exchangeError } = await supabase.auth.exchangeCodeForSession(code);
        if (exchangeError) {
          if (mounted) setError("This reset link has expired. Please request a new one.");
          return;
        }
      }

      // Recovery links generated by Supabase may use the implicit flow and
      // return the recovery session in the URL hash instead of a code query
      // parameter. The browser client is configured for PKCE, so it will not
      // consume those hash tokens automatically.
      if (!code) {
        const hashParams = new URLSearchParams(window.location.hash.slice(1));
        const accessToken = hashParams.get("access_token");
        const refreshToken = hashParams.get("refresh_token");
        if (accessToken && refreshToken) {
          const { error: sessionError } = await supabase.auth.setSession({
            access_token: accessToken,
            refresh_token: refreshToken
          });
          if (sessionError) {
            if (mounted) setError("This reset link has expired. Please request a new one.");
            return;
          }
          window.history.replaceState({}, document.title, `${window.location.pathname}${window.location.search}`);
        }
      }

      const { data, error: sessionError } = await supabase.auth.getSession();
      if (!mounted) return;
      if (sessionError || !data.session) {
        if (recoveryTokenHash) {
          // The server will verify this one-time token when the user submits
          // the new password. No browser session is required for this path.
          setReady(true);
          return;
        }
        setError("Open the password reset link from your email to continue.");
        return;
      }
      setReady(true);
    }

    const { data: authListener } = supabase.auth.onAuthStateChange((event, session) => {
      if (mounted && (event === "PASSWORD_RECOVERY" || session)) setReady(true);
    });

    prepareRecoverySession();

    return () => {
      mounted = false;
      authListener.subscription.unsubscribe();
    };
  }, []);

  async function handleSubmit(event: React.FormEvent) {
    event.preventDefault();
    setError(null);

    if (!ready && !tokenHash) {
      setError("Open the password reset link from your email to continue.");
      return;
    }
    if (password.length < 8) {
      setError("Password must be at least 8 characters.");
      return;
    }
    if (password !== confirmPassword) {
      setError("Passwords do not match.");
      return;
    }

    setLoading(true);
    let updateError: { message: string } | null = null;
    if (tokenHash) {
      const response = await fetch("/api/auth/reset-password", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ token_hash: tokenHash, password })
      });
      if (!response.ok) {
        const result = await response.json().catch(() => ({}));
        updateError = { message: result.error || "Unable to update password." };
      }
    } else {
      const supabase = createClient();
      const result = await supabase.auth.updateUser({
        password,
        data: { must_change_password: false }
      });
      updateError = result.error;
      await supabase.auth.signOut();
    }
    setLoading(false);

    if (updateError) {
      setError(updateError.message);
      return;
    }

    router.push("/login?reset=success");
  }

  return (
    <main className="flex min-h-screen items-center justify-center bg-ink-50 px-4">
      <div className="card w-full max-w-md">
        <div className="mb-6 text-center">
          <Link href="/" className="inline-flex items-center gap-2 text-xl font-bold text-ink-900">
            <img src="/favicon.svg" alt="Bizzio" className="h-8 w-8 rounded-lg" />
            Bizzio<span className="text-brand-500">.online</span>
          </Link>
          <p className="mt-2 text-sm text-ink-500">
            {firstLogin ? "Set your new password to continue" : "Set a new password"}
          </p>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div>
            <label className="label" htmlFor="password">New password</label>
            <input
              id="password"
              type="password"
              required
              minLength={8}
              className="input"
              disabled={loading}
              value={password}
              onChange={(event) => setPassword(event.target.value)}
            />
          </div>
          <div>
            <label className="label" htmlFor="confirm-password">Confirm new password</label>
            <input
              id="confirm-password"
              type="password"
              required
              minLength={8}
              className="input"
              disabled={loading}
              value={confirmPassword}
              onChange={(event) => setConfirmPassword(event.target.value)}
            />
          </div>

          {error && <p className="text-sm text-red-600">{error}</p>}
          {!ready && !error && (
            <p className="text-sm text-ink-500">Validating your reset link...</p>
          )}
          <button type="submit" disabled={loading} className="btn-primary w-full">
            {loading ? "Saving..." : "Set new password"}
          </button>
        </form>

        <p className="mt-6 text-center text-sm text-ink-500">
          <Link href="/login" className="font-medium text-brand-600 hover:underline">
            Back to login
          </Link>
        </p>
      </div>
    </main>
  );
}
