import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { formatINR, formatDate } from "@/lib/utils";
import { effectiveToggles, moduleEnabled } from "@/lib/permissions";

export const dynamic = "force-dynamic";

export default async function InvoiceReportPage() {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  const { data: employee } = await supabase.from("employees").select("company_id, is_finance, permission_overrides, permission_templates(toggles)").eq("user_id", user?.id).single();
  const template = Array.isArray((employee as any)?.permission_templates) ? (employee as any).permission_templates[0] : (employee as any)?.permission_templates;
  const toggles = effectiveToggles(template?.toggles, employee?.permission_overrides);
  const { data: company } = employee ? await supabase.from("companies").select("plan_id").eq("id", employee.company_id).maybeSingle() : { data: null };
  const { data: plan } = company?.plan_id ? await supabase.from("subscription_plans").select("feature_bundle, is_active").eq("id", company.plan_id).maybeSingle() : { data: null };
  if (!employee?.is_finance || !plan?.is_active || !moduleEnabled((plan?.feature_bundle ?? {}) as Record<string, any>, "finance") || !toggles.view_finance_invoice_report) return <div className="card p-6 text-sm text-red-600">Finance access is required to view the Invoice Report.</div>;
  const { data: invoices, error } = await supabase.from("invoices").select("id, invoice_number, title, total_amount, status, created_at, customer:customers(name), receipts(amount, taxable_amount, gst_amount, amount_received, tds_amount, discount_amount, post_to_ledger, non_posting_comment, reference_number, received_at)").eq("company_id", employee.company_id).order("created_at", { ascending: false });
  if (error) return <div className="card p-6 text-sm text-red-600">Unable to load the Invoice Report: {error.message}</div>;
  return <div><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold text-ink-900">Invoice Report</h1><p className="mt-1 text-sm text-ink-500">Invoice totals, receipt breakdown, payment status, and ledger posting status.</p></div><Link className="btn-secondary" href="/app/finance/invoices">Manage invoices</Link></div><div className="card mt-6 overflow-x-auto p-0"><table className="min-w-full text-left text-sm"><thead className="bg-ink-50 text-ink-600"><tr><th className="p-3">Invoice</th><th className="p-3">Customer</th><th className="p-3">Date</th><th className="p-3">Gross</th><th className="p-3">Taxable</th><th className="p-3">GST</th><th className="p-3">TDS</th><th className="p-3">Discount</th><th className="p-3">Net received</th><th className="p-3">Status</th><th className="p-3">Ledger</th><th className="p-3">Comment</th></tr></thead><tbody>{(invoices ?? []).map((invoice: any) => { const receipt = Array.isArray(invoice.receipts) ? invoice.receipts[0] : invoice.receipts; return <tr key={invoice.id} className="border-t border-ink-100 align-top"><td className="p-3"><Link className="text-brand-600 hover:underline" href={`/app/finance/invoices/${invoice.id}`}>{invoice.invoice_number}</Link><p className="text-xs text-ink-500">{invoice.title}</p></td><td className="p-3">{invoice.customer?.name || "—"}</td><td className="p-3 whitespace-nowrap">{formatDate(invoice.created_at)}</td><td className="p-3 font-semibold">{formatINR(receipt?.amount ?? invoice.total_amount)}</td><td className="p-3">{formatINR(receipt?.taxable_amount ?? 0)}</td><td className="p-3">{formatINR(receipt?.gst_amount ?? 0)}</td><td className="p-3">{formatINR(receipt?.tds_amount ?? 0)}</td><td className="p-3">{formatINR(receipt?.discount_amount ?? 0)}</td><td className="p-3">{receipt ? formatINR(receipt.amount_received) : "—"}</td><td className="p-3">{invoice.status}</td><td className="p-3">{invoice.status !== "paid" ? "—" : receipt?.post_to_ledger === false ? "Not posted" : "Posted"}</td><td className="max-w-sm p-3 text-ink-600">{receipt?.post_to_ledger === false ? receipt.non_posting_comment || "—" : "—"}</td></tr>; })}</tbody></table>{!invoices?.length && <p className="p-8 text-center text-sm text-ink-400">No invoices found.</p>}</div></div>;
}
