"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";

const EMPTY = { description: "", qty: 1, rate: 0, gst_percent: 18, gst_type: "cgst_sgst" };

export default function NewSalesOrderPage() {
  const router = useRouter();
  const [customers, setCustomers] = useState<any[]>([]);
  const [quotations, setQuotations] = useState<any[]>([]);
  const [customerId, setCustomerId] = useState("");
  const [title, setTitle] = useState("");
  const [quotationId, setQuotationId] = useState("");
  const [lines, setLines] = useState<any[]>([{ ...EMPTY }]);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [customerPoFile, setCustomerPoFile] = useState<File | null>(null);

  useEffect(() => { Promise.all([fetch("/api/app/finance/customers").then((r) => r.json()), fetch("/api/app/finance/quotations").then((r) => r.json())]).then(([c, q]) => { setCustomers(c || []); setQuotations((q || []).filter((item: any) => item.status === "accepted")); if (c?.[0]) setCustomerId(c[0].id); }); }, []);
  async function selectQuotation(id: string) { setQuotationId(id); if (!id) { setTitle(""); setLines([{ ...EMPTY }]); return; } const res = await fetch(`/api/app/finance/quotations/${id}`); const data = await res.json(); if (!res.ok) { setError(data.error || "Unable to load quotation."); return; } setTitle(data.quotation.title || ""); setCustomerId(data.quotation.customer_id); setLines((data.lineItems || []).map((line: any) => ({ description: line.description, qty: Number(line.qty), rate: Number(line.rate), gst_percent: Number(line.gst_percent), gst_type: line.gst_type }))); }
  function updateLine(index: number, key: string, value: string | number) { setLines((current) => current.map((line, i) => i === index ? { ...line, [key]: value } : line)); }
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(null); const res = await fetch("/api/app/finance/sales-orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, customer_id: customerId, quotation_id: quotationId || null, lines }) }); const json = await res.json(); if (!res.ok) { setLoading(false); setError(typeof json.error === "string" ? json.error : "Unable to create sales order."); return; } if (customerPoFile) { const supabase = createClient(); const { data: auth } = await supabase.auth.getUser(); const { data: userRow } = await supabase.from("users").select("company_id").eq("id", auth.user?.id).single(); const extension = customerPoFile.name.split(".").pop() || "bin"; const path = `${userRow?.company_id}/sales-orders/${json.salesOrder.id}-${Date.now()}.${extension}`; const upload = await supabase.storage.from("sales-order-documents").upload(path, customerPoFile, { upsert: false }); if (upload.error) { setLoading(false); setError("Sales Order created, but the customer PO could not be uploaded."); return; } const linked = await fetch(`/api/app/finance/sales-orders/${json.salesOrder.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ customer_po_attachment_path: upload.data.path, customer_po_attachment_name: customerPoFile.name }) }); if (!linked.ok) { setLoading(false); setError("Sales Order created, but the customer PO could not be linked."); return; } } setLoading(false); router.push(`/app/finance/sales-orders/${json.salesOrder.id}`); }
  return <div className="max-w-4xl"><h1 className="text-2xl font-bold text-ink-900">New Sales Order</h1><form onSubmit={submit} className="card mt-6 space-y-5"><div className="grid gap-4 md:grid-cols-2"><div><label className="label">Create from quotation (optional)</label><select className="input" value={quotationId} onChange={(e) => void selectQuotation(e.target.value)}><option value="">Enter items manually</option>{quotations.map((q) => <option key={q.id} value={q.id}>{q.quo_number} — {q.customer?.name}</option>)}</select></div><div><label className="label">Customer</label><select className="input" value={customerId} onChange={(e) => setCustomerId(e.target.value)} disabled={Boolean(quotationId)} required>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name}</option>)}</select></div></div><div><label className="label">Customer Purchase Order (optional)</label><input className="input" type="file" accept="image/*,.pdf,.doc,.docx,.xls,.xlsx" onChange={(e) => setCustomerPoFile(e.target.files?.[0] || null)} /><p className="mt-1 text-xs text-ink-500">Attach the PO received from the customer. PDF, image, Word, or Excel files are supported.</p></div><div className="space-y-4"><div className="flex items-center justify-between"><h2 className="font-semibold text-ink-800">Line Items</h2><button type="button" className="btn-secondary" onClick={() => setLines([...lines, { ...EMPTY }])}>Add Line</button></div>{lines.map((line, index) => <div className="rounded-lg border border-ink-100 p-4" key={index}><div className="grid gap-4 md:grid-cols-2"><div className="md:col-span-2"><label className="label">Description</label><input className="input" value={line.description} onChange={(e) => updateLine(index, "description", e.target.value)} required /></div><div><label className="label">Qty</label><input className="input" type="number" min="1" step="0.01" value={line.qty} onChange={(e) => updateLine(index, "qty", Number(e.target.value))} /></div><div><label className="label">Rate</label><input className="input" type="number" min="0" step="0.01" value={line.rate} onChange={(e) => updateLine(index, "rate", Number(e.target.value))} /></div><div><label className="label">GST %</label><input className="input" type="number" min="0" step="0.01" value={line.gst_percent} onChange={(e) => updateLine(index, "gst_percent", Number(e.target.value))} /></div><div><label className="label">GST Type</label><select className="input" value={line.gst_type} onChange={(e) => updateLine(index, "gst_type", e.target.value)}><option value="cgst_sgst">CGST + SGST</option><option value="igst">IGST</option></select></div></div></div>)}</div>{error && <p className="text-sm text-red-600">{error}</p>}<button className="btn-primary w-full" disabled={loading || !customerId}>{loading ? "Saving…" : "Save Sales Order"}</button></form></div>;
}
